### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by adam-dej** [janfietz/mfrc522#1]
Hello,

I found your library and I'd like to use it in my opensource project (which is licensed under the MIT license). However, I can't do so, because you have not specified under which license you are distributing your code. Would you please add a LICENSE file with a license of your choice?

**Comment by janfietz** [comment]
Hi,

sorry for my late response. I used a MIT license.

Please keep in in mind I tested only some of the available functions from the origin project.
